prep-javascript-objects | Rocky Truong
rockyt98/prep-0221-code-solutions pull request #11
Opened 2021-02-25 07:34 UTC by rockyt98

![image](https://user-images.githubusercontent.com/58172952/109118876-bd9bbf80-76f8-11eb-9e0f-054bfd831a0d.png)

![image](https://user-images.githubusercontent.com/58172952/109118898-c7252780-76f8-11eb-88fd-63ffe7228548.png)

2021-02-25 19:24 UTC, thebearingedge requested changes
Nice! Just a couple small changes.

2021-02-25 19:24 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +};
This part should be `myCar['owner'] = fullName` instead of assigning a whole new object.

2021-02-25 19:24 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +};
Same here.

2021-02-26 01:17 UTC, rockyt98 commented
![image](https://user-images.githubusercontent.com/58172952/109240934-47956800-778d-11eb-81e9-03d441d082d5.png)

![image](https://user-images.githubusercontent.com/58172952/109240997-6562cd00-778d-11eb-94d7-eeb34a7ad8f9.png)

2021-02-26 01:28 UTC, thebearingedge requested changes

2021-02-26 01:28 UTC, thebearingedge commented on prep-javascript-objects/main.js
> +console.log('My name is', (fullName), 'and I drive a', (myCar.year), (myCar.make), (myCar.model) + '.');
Try to create one string here using `+` to combine them together.

2021-02-26 01:55 UTC, rockyt98 commented
![image](https://user-images.githubusercontent.com/58172952/109243859-87128300-7792-11eb-86b8-1ece41c13b20.png)

![image](https://user-images.githubusercontent.com/58172952/109243947-b2956d80-7792-11eb-8906-d9d98a06cef4.png)

2021-02-26 20:45 UTC, thebearingedge approved these changes
Approved!

2021-02-27 02:15 UTC, merged